### ISSUE TITLE
Error on My Access page

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#148]
```
TypeError: Cannot read property 'id' of null
    at /app/dist/www/server/pages/devportal/access.js:2582:145
    at arrayAggregator (/app/node_modules/lodash/_arrayAggregator.js:17:32)
    at /app/node_modules/lodash/_createAggregator.js:19:12
    at AccessList (/app/dist/www/server/pages/devportal/access.js:2579:41)

```

**Comment by ikethecoder** [comment]
Close - duplicate.
