### ISSUE TITLE
Gateway Service updates not reflected in Portal

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#75]
Scenario: A user updates their Gateway configuration to include the `jwt-keycloak` plugin on the service and when they try and link the service to the environment, they are getting an error message: `"[<servicce>] missing or incomplete jwt-keycloak plugin`.

**Comment by ikethecoder** [comment]
Technical details:
```
debug: [batch.worker] keys triggering update ["service"]
debug: [ks.batch] [update] : GatewayRoute 99
debug: [ks.batch] [lookup] RESULT {"data":{"allGatewayServices":[]}}
error: [batch.connectOne] Lookup failed for allGatewayServices extForeignKey!
Error: Failed to find 6688c32e-2538-41ec-b8ea-6e5e66712517 in allGatewayServices
    at Object.<anonymous> (/app/dist/batch/transformations/connectOne.js:32:19)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/batch/transformations/connectOne.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
debug: [ks.batch] [update] RESULT {"data":{"updateGatewayRoute":{"id":"99"}}}
```

**Comment by ikethecoder** [comment]
The error is produced when a Gateway Service name is renamed - when using `deck`, a rename results in a new GUID and batch transformation matches on the GUID.  The portal has a unique constraint on `GatewayService.name`.
