### ISSUE TITLE
When requesting access giving an error that is difficult to troubleshoot

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/api-services-portal#788]
# API Services Portal Issue

## User Story

**As a** API Provider,<br>
**I want** to ensure that if there is an error when a Developer requests access that the reason is clear to the Developer and myself, the API Provider<br>
**so that** I can provide the best customer experience to my clients.

### ENV

- [ ] `DEV`
- [ ] `TEST`
- [X] `PROD`

### TESTCASE

-

### EXPECTED

-

### ACTUAL

-

**Comment by ikethecoder** [comment]
If for whatever reason the Generate Credentials fails, the error handling should be much better.

* Consumer : The Consumer only gets the error message "Unable to generate keys"

<img width="377" alt="image" src="https://user-images.githubusercontent.com/23747270/228092647-29f56e2b-3988-461b-9d1a-1d5b836fe777.png">

* API Provider : The API Provider only gets the error message "IssuerMisconfigError: undefined"

<img width="584" alt="image" src="https://user-images.githubusercontent.com/23747270/228092736-b53a11f5-6d39-4fba-9730-f24f431dca69.png">

* APS : The following error is logged in the Portal, but it is not very useful as it does not provide any details about what is happening..

```
2023-03-27 19:35:49 error: [general] Error - 400 Bad Request
2023-03-27 19:35:49 error: [general] ERROR {"error":"invalid_client","error_description":"Invalid client credentials"}
2023-03-27 19:35:49 error: [general] Added reason to error: {"reason":"invalid_client","status":"400 Bad Request"}
2023-03-27 19:35:49 error: [wf.Apply] Workflow Error IssuerMisconfigError: {"reason":"invalid_client","status":"400 Bad Request"}
at /app/dist/services/checkStatus.js:36:19
at Generator.next (<anonymous>)
at fulfilled (/app/dist/services/checkStatus.js:5:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
errors: [Array]
}
2023-03-27 19:35:50 error: [general] GraphQL Error: {"reason":"invalid_client","status":"400 Bad Request"}
GraphQL request:3:5
2 | mutation genCredential($id: ID!) {
3 | updateAccessRequest(id: $id, data: { credential: "NEW" }) {
| ^
4 | credential
```

**Comment by ikethecoder** [comment]
More detailed responses:

| Activity | Fix |
| - | - |
| response "401 Unauthorized" reason "unauthorized_client" description "Client not enabled to retrieve service account" | Enable Service Account |
| response "403 Forbidden" reason "insufficient_scope" description "Forbidden" | Grant Service Account Roles `manage-clients` and `manage-users` |
